# 生产环境配置
server:
  # 服务端口
  port: 5000

spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    url: jdbc:mysql://localhost:3306/sky_blog?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "123456"
  # redis 配置
  redis:
    host: localhost # redis 主机地址
    port: 6379 # redis 端口号
    database: 8 # 操作的 redis 数据库(0-15)
    password: # redis 连接密码
    timeout: 20s # 超时时间
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数
        max-wait: -1 # 连接池最大阻塞等待时间
        max-idle: 10 # 连接池最大空闲连接
        min-idle: 2 # 连接池最小空闲连接

# 开启权限拦截
auth:
  enabled: true

# 开启请求日志记录
request-log:
  enabled: true