# 开发环境配置
server:
  # 服务端口
  port: 5000

spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    url: jdbc:mysql://localhost:3306/sky_blog?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "123456"

# 开启权限拦截
auth:
  enabled: true

# 开启 http 请求日志记录
request-log:
  enabled: true

logging:
  level:
    # web 信息日志记录
    web: debug
    # SQL 日志记录
    io.github.talelin.latticy.mapper: debug